<?xml version="1.0"?>
<package format="2">
  <name>battery_simulator</name>
  <version>0.0.0</version>
  <description>Simulates a Li-ion battery discharging over time, draining faster under cmd_vel load, publishing sensor_msgs/BatteryState</description>

  <maintainer email="154484150+starina-chan@users.noreply.github.com">starina-chan</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
